# Generated by Django 4.2.7 on 2023-11-05 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0002_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="API.course"
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(related_name="groups", to="API.student"),
                ),
            ],
        ),
    ]
