# Generated by Django 4.2.7 on 2023-11-06 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0004_group_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="group",
            field=models.CharField(
                choices=[("A", "Group A"), ("B", "Group B"), ("C", "Group C")],
                max_length=1,
            ),
        ),
        migrations.DeleteModel(
            name="Group",
        ),
    ]
